name: Publish HTML

on:
  push:
    branches: [ 'main' ]
    paths: [ 'site/**' ]

on: workflow_dispatch

jobs:

  build:

    name: Copy HTML Files To S3
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}

    - name: Set up Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        pip install Jinja2

    - name: Generate Rendered HTML Files
      working-directory: site
      run: |
        python render_pages.py

    - name: Update HTML Files in S3
      working-directory: site/rendered
      run: |
        aws s3 cp . s3://brianwtracey.com/ --recursive

    - name: Update Favicon in S3
      working-directory: site
      run: |
        aws s3 cp favicon.png s3://brianwtracey.com/
