name: Lambda CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    name: Build Image, Push to ECR, and update Lambda
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      id: buildx
      with:
        install: true


    - name: Build, Tag, and Push Image to AWS ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: pixlet
        IMAGE_TAG: latest
      run: |
        docker build --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --platform linux/arm64 .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Lambda With Newest Image
      env:
        LAMBDA_NAME: pixlet-messages
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: pixlet
        IMAGE_TAG: latest
      run: |
        aws lambda update-function-code \
        --function-name $LAMBDA_NAME \
        --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
